### ISSUE TITLE
Add support for bulk sending of SMSs with Sendega backend

### ISSUE THREAD

**Issue by timkurvers** [hyperoslo/cellular#14]
From [Sendega's API documentation](http://controlpanel.sendega.no/Content/Sendega%20-%20API%20documentation%20v2.3.pdf):

![screen shot 2014-11-14 at 10 42 23](https://cloud.githubusercontent.com/assets/378235/5043903/f965f2b2-6bea-11e4-9801-b56a9cad8583.png)

Any ideas on implementation? We could theoretically introduce `Cellular::SMS#recipients` and then have the backends handle it accordingly.

**Comment by JozoSalt** [comment]
Tried to do what was explained above, but I have a question:
* Sendenga only supports 100 destinations per request. That means in some cases it will do multiple requests 
* Coolsms only support one destination per request. That means each destination in recipients option will be a request. 

So my question is, how do you want to handle response ? for now I have just returned the first response in the same way it used to do.  If you want, I can create a pull-request, and we can go from there ?

**Comment by jgorset** [comment]
Woa! You're fast, @JozoSalt! Also that's a good question. Feel free to create a pull request with what you have so far, though, and we can take it from there.
