### ISSUE TITLE
Ensure sending over TLSv1 towards Sendega

### ISSUE THREAD

**Issue by sindrenm** [hyperoslo/cellular#22]
Sending texts through Sendega doesn't work by default, unless we specify the default SSL version for Excon to be `TLSv1`:

``` ruby
Excon.defaults[:ssl_version] = :TLSv1
```

While we could specify this in the application, it'd be better to set it specifically when sending through Sendega, as setting it globally in the application might cause an issue elsewhere.

**Comment by timkurvers** [comment]
When using Cellular stand-alone this issue does not arise. This leads us to believe that dependencies may be setting global defaults.

One of these gems is `fog`, from a certain version upwards. Specifying the default `:TLSv1` wouldn't really do any harm other than locking it for the future.
